# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
    - sudo apt update && sudo apt -y install python3-pip valac gobject-introspection valadoc libgirepository1.0-dev libjson-glib-dev
    - sudo pip3 install meson
  script: 
    - mkdir build && cd build && meson .. && ninja
    - ./oparl_test
  artifacts:
    paths:
      - liboparl.so
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

