# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "oparl")
set(oparl_VERSION "0.0.0")
set(soversion "0")
set(required_pkgs
  "gio-2.0"
  "glib-2.0"
  "gobject-2.0"
  "json-glib-1.0"
)
set(srcfiles
  "src/lib.vala"
)
set(vapifiles
)
set(uifiles
)
