# This file was auto generated by Valama 0.1.2. Do not modify it.
set(project_name "OParl")
set(OParl_VERSION "0.2.0")
set(API_VERSION "0.2")
set(soversion "0")
set(required_pkgs
  "gio-2.0"
  "glib-2.0"
  "gobject-2.0"
  "json-glib-1.0"
)
set(srcfiles
  "src/lib.vala"
  "src/unfinished.vala"
  "src/body.vala"
  "src/person.vala"
  "src/membership.vala"
  "src/meeting.vala"
  "src/system.vala"
  "src/object.vala"
  "src/organization.vala"
)
set(vapifiles
)
set(uifiles
)
